import type { UatCase } from "../../schema.js";
import { A13, A14 } from "../../fixtures/facts.js";
import { turn as t, page, knowledge, calculate, kApprox, kMax, filter } from "../helpers.js";
const make = (n: number, scenario: string, turns: UatCase["turns"], tags: string[]): UatCase => ({ id: `DESIGN-${String(n).padStart(3, "0")}`, persona: "DESIGN_INSTITUTE", scenario, tags, turns });
export const designCases: UatCase[] = [
  make(1, "K近似：区分图集与上限", [t("I型VICP薄抹灰K≈0.3有哪些构造？", { query: { filters: kApprox }, expectedCandidate: A13 }), t("刚才A1-3 18mm的0.303是图集值还是计算值？", { resultType: "REFERENCE", answerFacts: [{ pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.303 }] }), page()], ["APPROX"]),
  make(2, "K上限：排除0.303", [t("K控制在0.3以内有哪些方案？", { query: { filters: kMax }, expectedCandidate: A14 }), t("限定18mm的呢？", { query: { thicknessMm: 18 }, candidateCount: 0, inheritPreviousFilters: true }), t("厚度改成20mm", { query: { thicknessMm: 20 }, expectedCandidate: A14, inheritPreviousFilters: true })], ["MAX_LIMIT"]),
  make(3, "总热阻下限保留边界", [t("总热阻不得低于3.3有哪些构造？", { query: { filters: [filter("TOTAL_R", "MIN_LIMIT", 3.3)] }, expectedCandidate: A14 }), t("总R改成3.5以上", { query: { filters: [filter("TOTAL_R", "MIN_LIMIT", 3.5)] } }), page()], ["TOTAL_R"]),
  make(4, "产品热阻与总热阻分开核验", [t("产品R做到2.9左右的I型方案", { query: { filters: [filter("PRODUCT_R", "APPROX", 2.9)] }, expectedCandidate: A13 }), t("刚才A1-3的总热阻是多少？", { reusePreviousCandidate: true, answerFacts: [{ pattern: "(?:总热阻|总R)[^\\d]{0,20}", value: 3.297 }] }), page()], ["PRODUCT_R", "METRIC_CONFUSION"]),
  make(5, "厚度与双指标AND", [t("厚度控制在18到25mm，传热系数不应大于0.3，总热阻不得低于3.3，有哪些构造？", { query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("TOTAL_R", "MIN_LIMIT", 3.3)], thicknessMin: 18, thicknessMax: 25 }, expectedCandidate: A14 }), t("总R做到3.5以上", { query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("TOTAL_R", "MIN_LIMIT", 3.5)] } }), page()], ["AND"]),
  make(6, "厚度双边范围与只取消上限", [t("厚度18到25mm，K0.3左右有哪些方案？", { query: { filters: kApprox, thicknessMin: 18, thicknessMax: 25 } }), t("取消厚度上限", { query: { thicknessMin: 18, thicknessMax: undefined }, inheritPreviousFilters: true }), t("25以上呢？", { query: { thicknessMin: 25 }, inheritPreviousFilters: true, candidateCount: 0 })], ["RANGE"]),
  make(7, "构造层参数可核验", [t("A1-3 18mm图集参数给我", { expectedCandidate: A13 }), knowledge("A1-3基层材料和厚度是什么？", { intent: "REFERENCE_LOOKUP", answerIncludes: ["灰砂砖", "240"] }), page()], ["LAYERS"]),
  make(8, "导热系数单位和参数来源", [knowledge("I型VICP的导热系数λ是多少？", { intent: "REFERENCE_LOOKUP", answerFacts: [{ pattern: "(?:λ|导热系数)[^\\d]{0,30}", value: 0.005 }], answerIncludes: ["W"] }), knowledge("这个是当量导热系数吗，来源是什么？", { intent: "REFERENCE_LOOKUP", answerIncludes: ["当量"] }), t("用这个产品找K0.3左右的方案", { query: { filters: kApprox }, expectedCandidate: A13 })], ["LAMBDA"]),
  make(9, "修正系数与产品R公式解释", [t("A1-3 18mm的参数", { expectedCandidate: A13 }), knowledge("I型产品的修正系数α是多少？", { intent: "REFERENCE_LOOKUP", answerFacts: [{ pattern: "(?:α|修正系数)[^\\d]{0,30}", value: 1.25 }] }), knowledge("18mm为什么产品热阻是2.880？请展开公式", { intent: "REFERENCE_LOOKUP", answerIncludes: ["0.018", "0.005", "1.25", "2.88"] })], ["ALPHA", "FORMULA"]),
  make(10, "内外表面换热阻", [t("A1-3 18mm的图集参数", { expectedCandidate: A13 }), knowledge("Ri和Re分别是多少？", { intent: "GENERAL", answerFacts: [{ pattern: "Ri[^\\d]{0,30}", value: 0.11 }, { pattern: "Re[^\\d]{0,30}", value: 0.04 }] }), knowledge("总热阻包括这两个表面换热阻吗？", { intent: "REFERENCE_LOOKUP", answerIncludes: ["表面"] })], ["SURFACE_R"]),
  make(11, "图集双R与K精度", [t("A1-3 I型18mm图集原始行给我", { expectedCandidate: A13, resultType: "REFERENCE" }), t("刚才的产品R、总R、K分别是多少？", { reusePreviousCandidate: true, answerFacts: [{ pattern: "(?:产品层?热阻|产品R)[^\\d]{0,20}", value: 2.880 }, { pattern: "(?:总热阻|总R)[^\\d]{0,20}", value: 3.297 }, { pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.303 }] }), page()], ["REFERENCE_VALUE"]),
  make(12, "正式计算与冻结快照", [t("A1-3 I型18mm图集参数", { expectedCandidate: A13 }), calculate("请按当量法正式计算A1-3 I型18mm的K", { answerFacts: [{ pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.303, tolerance: 0.0005 }] }), calculate("重新计算A1-3 I型22mm，给出计算值", { answerFacts: [{ pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.254, tolerance: 0.0005 }] })], ["CALCULATED", "SNAPSHOT"]),
  make(13, "查表转正式计算", [t("A1-3 18mm的参数给我", { expectedCandidate: A13 }), t("刚才这个0.303是图集值还是计算值？", { resultType: "REFERENCE" }), calculate("如果换成22mm重新算", { answerIncludes: ["计算"] })], ["LOOKUP_TO_CALC"]),
  make(14, "厚度变化必须重新计算", [t("A1-3 I型18mm的方案参数", { expectedCandidate: A13 }), calculate("A1-3改成22mm重新计算", { answerFacts: [{ pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.254, tolerance: 0.0005 }] }), calculate("帮我算一下这个墙体20mm后的K", { answerFacts: [{ pattern: "(?:K|传热系数)[^\\d]{0,20}", value: 0.276, tolerance: 0.0005 }] })], ["THICKNESS_CALC"]),
  make(15, "原始印刷页而非物理页猜测", [t("I型18mm有没有K0.3左右的图集方案？", { expectedCandidate: A13 }), page("第一个呢，原图哪一页？"), page("把刚才那页给我看看")], ["SOURCE_PAGE"]),
  make(16, "上海项目合规不能由筛选推出", [t("A1-3 18mm的参数", { expectedCandidate: A13 }), calculate("上海这个项目K=0.3够不够？", { intent: "COMPLIANCE", operation: undefined, resultType: undefined, toolsAny: ["thermal", "search_knowledge"], clarification: true }), knowledge("没有正式标准就先不要下达标结论，需要补什么？", { intent: "COMPLIANCE", toolsAny: [], clarification: true })], ["COMPLIANCE"]),
  make(17, "标准地区依据不足的克制回答", [knowledge("上海外墙是否满足要求？", { intent: "COMPLIANCE", toolsAny: ["search_knowledge", "thermal"], clarification: true }), knowledge("这个参数符合哪个标准？K=0.3", { intent: "COMPLIANCE", toolsAny: ["search_knowledge", "thermal"], clarification: true }), t("那先只查K不超过0.3的正式方案", { query: { filters: kMax }, expectedCandidate: A14 })], ["STANDARD", "REGION"]),
  make(18, "冲突参数与OR必须澄清", [t("厚度25到18mm，K0.3左右有哪些构造？", { toolsAny: [], clarification: true }), t("改为18到25mm，K<=0.3或者总R>=3.3", { toolsAny: [], clarification: true }), t("是同时满足，厚度18到25mm，K<=0.3且总R>=3.3", { query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("TOTAL_R", "MIN_LIMIT", 3.3)], thicknessMin: 18, thicknessMax: 25 }, expectedCandidate: A14 })], ["CONFLICT", "OR"]),
  make(19, "无结果说明全部硬条件", [t("I型18mm以内，K<=0.3且总R>=3.3有哪些构造？", { candidateCount: 0, query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("TOTAL_R", "MIN_LIMIT", 3.3)], thicknessMax: 18 } }), t("放宽到20", { query: { thicknessMax: 20 }, expectedCandidate: A14, inheritPreviousFilters: true }), page()], ["NO_MATCH_REASON"]),
  make(20, "多轮指标修改、取消、恢复", [t("K<=0.3，总R>=3.3，20mm以内", { query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("TOTAL_R", "MIN_LIMIT", 3.3)], thicknessMax: 20 } }), t("取消总R，厚度放宽到25", { query: { filters: kMax, thicknessMax: 25 } }), t("再加产品R做到2.9以上", { query: { filters: [filter("K", "MAX_LIMIT", 0.3), filter("PRODUCT_R", "MIN_LIMIT", 2.9)], thicknessMax: 25 } }), t("不限制厚度，K改成0.3左右", { query: { filters: [filter("K", "APPROX", 0.3), filter("PRODUCT_R", "MIN_LIMIT", 2.9)], thicknessMax: undefined } })], ["STATE", "LOCAL_UPDATE"])
];
