/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAiComposer: typeof import('./components/ai/AiComposer.vue')['default']
    AiAiFeedbackPanel: typeof import('./components/ai/AiFeedbackPanel.vue')['default']
    AiAiMessageList: typeof import('./components/ai/AiMessageList.vue')['default']
    AiAiSharePanel: typeof import('./components/ai/AiSharePanel.vue')['default']
    AiAiShareSelectBar: typeof import('./components/ai/AiShareSelectBar.vue')['default']
    AiAiWelcomeHero: typeof import('./components/ai/AiWelcomeHero.vue')['default']
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    HomeHomeEntryGrid: typeof import('./components/home/HomeEntryGrid.vue')['default']
    HomeHomeHero: typeof import('./components/home/HomeHero.vue')['default']
    HomeHomeSectionShell: typeof import('./components/home/HomeSectionShell.vue')['default']
    HomeHomeWelcome: typeof import('./components/home/HomeWelcome.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdAvatar: typeof import('@wot-ui/ui/components/wd-avatar/wd-avatar.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdCountTo: typeof import('@wot-ui/ui/components/wd-count-to/wd-count-to.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['default']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSearch: typeof import('@wot-ui/ui/components/wd-search/wd-search.vue')['default']
    WdSkeleton: typeof import('@wot-ui/ui/components/wd-skeleton/wd-skeleton.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
