import type { FastifyInstance } from "fastify";
import type { ZodTypeProvider } from "fastify-type-provider-zod";
import { and, asc, count, desc, eq, ilike, inArray, isNull } from "drizzle-orm";
import { z } from "zod";
import { cronExecutions, cronJobs, departments, dictionaryItems, dictionaries, loginLogs, posts, refreshTokens, roleDepartments, roles, userDepartments, userRoles, users } from "../../db/schema.js";
import { assertPermission } from "../../shared/permission-guard.js";
import { getPagination, paginationQuerySchema } from "../../shared/pagination.js";
import { NotFoundError, ForbiddenError } from "../../shared/errors.js";
import { ok } from "../../shared/response.js";
import { AUDIT_ACTIONS } from "../../shared/constants.js";
import { writeAuditLog } from "../audit-logs/audit-log.service.js";

const idParams = z.object({ id: z.uuid("ID 格式不正确") });
const idsBody = z.object({ ids: z.array(z.uuid()).max(1000) });
const statusBody = z.object({ enabled: z.boolean() });
const postBody = z.object({ name: z.string().trim().min(1, "请输入岗位名称").max(120), code: z.string().trim().regex(/^[a-z][a-z0-9_.-]{1,79}$/, "岗位编码格式不正确"), sortOrder: z.number().int().default(0), enabled: z.boolean().default(true), remark: z.string().max(1000).nullable().optional() });
const deptBody = z.object({ parentId: z.uuid("上级部门 ID 格式不正确").nullable().optional(), code: z.string().trim().min(2).max(80), name: z.string().trim().min(1, "请输入部门名称").max(120), leader: z.string().max(120).nullable().optional(), phone: z.string().max(32).nullable().optional(), email: z.string().email("邮箱格式不正确").max(255).nullable().optional(), sortOrder: z.number().int().default(0), enabled: z.boolean().default(true) });
const rolePatch = z.object({ name: z.string().trim().min(1).max(120).optional(), description: z.string().max(1000).nullable().optional(), dataScope: z.enum(["ALL", "DEPT", "DEPT_AND_CHILDREN", "SELF", "CUSTOM", "PROJECT_OWNER"]).optional(), enabled: z.boolean().optional() }).refine((v) => Object.keys(v).length > 0, "至少需要修改一个字段");
const dictPatch = z.object({ name: z.string().trim().min(1).max(120).optional(), description: z.string().max(1000).nullable().optional(), enabled: z.boolean().optional() }).refine((v) => Object.keys(v).length > 0, "至少需要修改一个字段");
const itemBody = z.object({ value: z.string().trim().min(1).max(120), label: z.string().trim().min(1).max(120), sortOrder: z.number().int().default(0), enabled: z.boolean().default(true), metadata: z.record(z.string(), z.unknown()).optional() });
const cronBody = z.object({ name: z.string().trim().min(1).max(120), jobType: z.enum(["maintenance", "document_cleanup", "audit_cleanup"]), cronExpression: z.string().trim().min(5).max(120), queueName: z.enum(["maintenance"]), payload: z.record(z.string(), z.unknown()).optional(), status: z.enum(["PAUSED", "RUNNING", "DISABLED"]).default("PAUSED") });

function assertWhiteListKey(key: string) {
  const allowed = ["auth:", "dict:", "ai:rate:", "ai:quota:", "captcha:"];
  if (!allowed.some((prefix) => key.startsWith(prefix))) throw new ForbiddenError("当前 Key 不在允许操作的缓存白名单中");
}

export async function platformOpsRoutes(app: FastifyInstance) {
  const route = app.withTypeProvider<ZodTypeProvider>();

  route.get("/posts", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 岗位管理"], summary: "获取岗位列表", querystring: paginationQuerySchema } }, async (request) => {
    await assertPermission(request, "system:post:list");
    const { skip, take } = getPagination(request.query.page, request.query.pageSize);
    const [items, [totalRow]] = await Promise.all([app.db.select().from(posts).orderBy(asc(posts.sortOrder), asc(posts.createdAt)).offset(skip).limit(take), app.db.select({ value: count() }).from(posts)]);
    return ok(request, { items, total: totalRow?.value ?? 0, page: request.query.page, pageSize: request.query.pageSize });
  });
  route.post("/posts", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 岗位管理"], summary: "创建岗位", body: postBody } }, async (request) => {
    const actor = await assertPermission(request, "system:post:add");
    const [post] = await app.db.insert(posts).values(request.body).returning();
    await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.POST_CREATED, targetType: "post", targetId: post!.id, afterJson: post });
    return ok(request, { message: "岗位创建成功", post });
  });
  route.patch("/posts/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 岗位管理"], summary: "修改岗位", params: idParams, body: postBody.partial() } }, async (request) => {
    const actor = await assertPermission(request, "system:post:edit");
    const [before] = await app.db.select().from(posts).where(eq(posts.id, request.params.id)).limit(1); if (!before) throw new NotFoundError("岗位不存在");
    const [post] = await app.db.update(posts).set({ ...request.body, updatedAt: new Date() }).where(eq(posts.id, before.id)).returning();
    await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.POST_UPDATED, targetType: "post", targetId: before.id, beforeJson: before, afterJson: post });
    return ok(request, { message: "岗位修改成功", post });
  });
  route.patch("/posts/:id/status", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 岗位管理"], summary: "修改岗位状态", params: idParams, body: statusBody } }, async (request) => {
    const actor = await assertPermission(request, "system:post:edit");
    const [post] = await app.db.update(posts).set({ enabled: request.body.enabled, updatedAt: new Date() }).where(eq(posts.id, request.params.id)).returning(); if (!post) throw new NotFoundError("岗位不存在");
    await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.POST_STATUS_CHANGED, targetType: "post", targetId: post.id, afterJson: { enabled: post.enabled } }); return ok(request, { message: "岗位状态修改成功", post });
  });
  route.delete("/posts/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 岗位管理"], summary: "删除岗位", params: idParams } }, async (request) => {
    const actor = await assertPermission(request, "system:post:remove");
    const [post] = await app.db.delete(posts).where(eq(posts.id, request.params.id)).returning(); if (!post) throw new NotFoundError("岗位不存在");
    await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.POST_DELETED, targetType: "post", targetId: post.id, beforeJson: post }); return ok(request, { message: "岗位删除成功" });
  });

  route.patch("/roles/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "修改角色", params: idParams, body: rolePatch } }, async (request) => {
    const actor = await assertPermission(request, "system:role:edit"); const [before] = await app.db.select().from(roles).where(eq(roles.id, request.params.id)).limit(1); if (!before) throw new NotFoundError("角色不存在");
    const [role] = await app.db.update(roles).set({ ...request.body, updatedAt: new Date() }).where(eq(roles.id, before.id)).returning(); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.RBAC_ROLE_UPDATED, targetType: "role", targetId: before.id, beforeJson: before, afterJson: role }); return ok(request, { message: "角色修改成功", role });
  });
  route.patch("/roles/:id/status", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "修改角色状态", params: idParams, body: statusBody } }, async (request) => {
    const actor = await assertPermission(request, "system:role:edit"); const [role] = await app.db.update(roles).set({ enabled: request.body.enabled, updatedAt: new Date() }).where(eq(roles.id, request.params.id)).returning(); if (!role) throw new NotFoundError("角色不存在"); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.RBAC_ROLE_STATUS_CHANGED, targetType: "role", targetId: role.id, afterJson: { enabled: role.enabled } }); return ok(request, { message: "角色状态修改成功", role });
  });
  route.delete("/roles/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "删除角色", params: idParams } }, async (request) => {
    const actor = await assertPermission(request, "system:role:remove"); const [role] = await app.db.delete(roles).where(eq(roles.id, request.params.id)).returning(); if (!role) throw new NotFoundError("角色不存在"); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.RBAC_ROLE_DELETED, targetType: "role", targetId: role.id, beforeJson: role }); return ok(request, { message: "角色删除成功" });
  });
  route.get("/roles/export", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "导出角色 CSV" } }, async (request, reply) => {
    await assertPermission(request, "system:role:export"); const rows = await app.db.select().from(roles).orderBy(asc(roles.code)); const csv = ["角色名称,权限字符,数据权限,状态,描述", ...rows.map((row) => [row.name, row.code, row.dataScope, row.enabled ? "启用" : "停用", row.description ?? ""].map((value) => { const text = String(value); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }).join(","))].join("\n"); return reply.type("text/csv; charset=utf-8").send(`\uFEFF${csv}`);
  });
  route.put("/roles/:id/departments", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "设置角色数据部门范围", params: idParams, body: idsBody } }, async (request) => {
    const actor = await assertPermission(request, "system:role:data-scope"); const [role] = await app.db.select().from(roles).where(eq(roles.id, request.params.id)).limit(1); if (!role) throw new NotFoundError("角色不存在");
    await app.db.transaction(async (tx) => { await tx.delete(roleDepartments).where(eq(roleDepartments.roleId, role.id)); if (request.body.ids.length) await tx.insert(roleDepartments).values(request.body.ids.map((departmentId) => ({ roleId: role.id, departmentId }))); await writeAuditLog({ db: tx, request, actor, action: AUDIT_ACTIONS.RBAC_ROLE_DATA_SCOPE_CHANGED, targetType: "role", targetId: role.id, afterJson: { departmentIds: request.body.ids } }); }); return ok(request, { message: "角色数据权限设置成功" });
  });
  route.get("/roles/:id/users", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 角色权限"], summary: "获取角色用户", params: idParams, querystring: paginationQuerySchema } }, async (request) => {
    await assertPermission(request, "system:role:list"); const { skip, take } = getPagination(request.query.page, request.query.pageSize); const rows = await app.db.select({ id: users.id, displayName: users.displayName, phone: users.phone, status: users.status }).from(users).innerJoin(userRoles, eq(userRoles.userId, users.id)).where(and(eq(userRoles.roleId, request.params.id), isNull(users.deletedAt))).offset(skip).limit(take); return ok(request, { items: rows, page: request.query.page, pageSize: request.query.pageSize });
  });

  route.get("/departments/tree", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 部门管理"], summary: "获取部门树" } }, async (request) => {
    await assertPermission(request, "system:dept:list"); const rows = await app.db.select().from(departments).where(isNull(departments.deletedAt)).orderBy(asc(departments.sortOrder), asc(departments.name)); const map = new Map<string | null, any[]>(); for (const row of rows) { const list = map.get(row.parentId) ?? []; list.push({ ...row, children: [] }); map.set(row.parentId, list); } const attach = (items: any[]): any[] => items.map((item) => ({ ...item, children: attach(map.get(item.id) ?? []) })); return ok(request, { items: attach(map.get(null) ?? []) });
  });
  route.patch("/departments/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 部门管理"], summary: "修改部门", params: idParams, body: deptBody.partial() } }, async (request) => {
    const actor = await assertPermission(request, "system:dept:edit"); const [before] = await app.db.select().from(departments).where(eq(departments.id, request.params.id)).limit(1); if (!before) throw new NotFoundError("部门不存在"); if (request.body.parentId === before.id) throw new ForbiddenError("部门上级不能是自身"); const [department] = await app.db.update(departments).set({ ...request.body, updatedAt: new Date() }).where(eq(departments.id, before.id)).returning(); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DEPARTMENT_UPDATED, targetType: "department", targetId: before.id, beforeJson: before, afterJson: department }); return ok(request, { message: "部门修改成功", department });
  });
  route.patch("/departments/:id/status", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 部门管理"], summary: "修改部门状态", params: idParams, body: statusBody } }, async (request) => { const actor = await assertPermission(request, "system:dept:edit"); const [department] = await app.db.update(departments).set({ enabled: request.body.enabled, updatedAt: new Date() }).where(eq(departments.id, request.params.id)).returning(); if (!department) throw new NotFoundError("部门不存在"); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DEPARTMENT_STATUS_CHANGED, targetType: "department", targetId: department.id, afterJson: { enabled: department.enabled } }); return ok(request, { message: "部门状态修改成功", department }); });
  route.delete("/departments/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 部门管理"], summary: "删除部门", params: idParams } }, async (request) => { const actor = await assertPermission(request, "system:dept:remove"); const [child] = await app.db.select({ id: departments.id }).from(departments).where(and(eq(departments.parentId, request.params.id), isNull(departments.deletedAt))).limit(1); const [member] = await app.db.select({ userId: userDepartments.userId }).from(userDepartments).where(eq(userDepartments.departmentId, request.params.id)).limit(1); if (child || member) throw new ForbiddenError("部门存在下级部门或用户，请先迁移后再删除"); const [department] = await app.db.update(departments).set({ deletedAt: new Date(), enabled: false, updatedAt: new Date() }).where(eq(departments.id, request.params.id)).returning(); if (!department) throw new NotFoundError("部门不存在"); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DEPARTMENT_DELETED, targetType: "department", targetId: department.id, beforeJson: department }); return ok(request, { message: "部门删除成功" }); });

  route.patch("/dictionaries/:id", { preHandler: [app.authenticate], schema: { tags: ["字典管理"], summary: "修改字典", params: idParams, body: dictPatch } }, async (request) => { const actor = await assertPermission(request, "system:dict:edit"); const [before] = await app.db.select().from(dictionaries).where(eq(dictionaries.id, request.params.id)).limit(1); if (!before) throw new NotFoundError("字典不存在"); const [dictionary] = await app.db.update(dictionaries).set({ ...request.body, updatedAt: new Date() }).where(eq(dictionaries.id, before.id)).returning(); await app.redis.del(`dict:${before.code}`); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DICTIONARY_UPDATED, targetType: "dictionary", targetId: before.id, beforeJson: before, afterJson: dictionary }); return ok(request, { message: "字典修改成功", dictionary }); });
  route.delete("/dictionaries/:id", { preHandler: [app.authenticate], schema: { tags: ["字典管理"], summary: "删除字典", params: idParams } }, async (request) => { const actor = await assertPermission(request, "system:dict:remove"); const [dictionary] = await app.db.delete(dictionaries).where(eq(dictionaries.id, request.params.id)).returning(); if (!dictionary) throw new NotFoundError("字典不存在"); await app.redis.del(`dict:${dictionary.code}`); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DICTIONARY_DELETED, targetType: "dictionary", targetId: dictionary.id, beforeJson: dictionary }); return ok(request, { message: "字典删除成功" }); });
  route.get("/dictionaries/:id/items", { preHandler: [app.authenticate], schema: { tags: ["字典管理"], summary: "获取字典项", params: idParams } }, async (request) => { await assertPermission(request, "system:dict:list"); return ok(request, { items: await app.db.select().from(dictionaryItems).where(eq(dictionaryItems.dictionaryId, request.params.id)).orderBy(asc(dictionaryItems.sortOrder), asc(dictionaryItems.createdAt)) }); });
  route.patch("/dictionaries/:id/items/:itemId", { preHandler: [app.authenticate], schema: { tags: ["字典管理"], summary: "修改字典项", params: z.object({ id: z.uuid(), itemId: z.uuid() }), body: itemBody.partial() } }, async (request) => { const actor = await assertPermission(request, "system:dict:edit"); const [item] = await app.db.update(dictionaryItems).set({ ...request.body, updatedAt: new Date() }).where(and(eq(dictionaryItems.id, request.params.itemId), eq(dictionaryItems.dictionaryId, request.params.id))).returning(); if (!item) throw new NotFoundError("字典项不存在"); await app.redis.del(`dict:${request.params.id}`); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DICTIONARY_ITEM_UPDATED, targetType: "dictionary_item", targetId: item.id, afterJson: item }); return ok(request, { message: "字典项修改成功", item }); });
  route.delete("/dictionaries/:id/items/:itemId", { preHandler: [app.authenticate], schema: { tags: ["字典管理"], summary: "删除字典项", params: z.object({ id: z.uuid(), itemId: z.uuid() }) } }, async (request) => { const actor = await assertPermission(request, "system:dict:remove"); const [item] = await app.db.delete(dictionaryItems).where(and(eq(dictionaryItems.id, request.params.itemId), eq(dictionaryItems.dictionaryId, request.params.id))).returning(); if (!item) throw new NotFoundError("字典项不存在"); await app.redis.del(`dict:${request.params.id}`); await writeAuditLog({ db: app.db, request, actor, action: AUDIT_ACTIONS.DICTIONARY_ITEM_DELETED, targetType: "dictionary_item", targetId: item.id, beforeJson: item }); return ok(request, { message: "字典项删除成功" }); });

  route.get("/login-logs", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "查询登录日志", querystring: paginationQuerySchema } }, async (request) => { await assertPermission(request, "monitor:login-log:list"); const { skip, take } = getPagination(request.query.page, request.query.pageSize); const [items, [totalRow]] = await Promise.all([app.db.select().from(loginLogs).orderBy(desc(loginLogs.createdAt)).offset(skip).limit(take), app.db.select({ value: count() }).from(loginLogs)]); return ok(request, { items, total: totalRow?.value ?? 0, page: request.query.page, pageSize: request.query.pageSize }); });

  route.get("/online-users", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "查询在线用户" } }, async (request) => { await assertPermission(request, "monitor:online:list"); const rows = await app.db.select({ id: refreshTokens.id, userId: refreshTokens.userId, clientType: refreshTokens.clientType, ip: refreshTokens.ip, userAgent: refreshTokens.userAgent, accessJti: refreshTokens.accessJti, createdAt: refreshTokens.createdAt, expiresAt: refreshTokens.expiresAt, displayName: users.displayName }).from(refreshTokens).innerJoin(users, eq(users.id, refreshTokens.userId)).where(and(isNull(refreshTokens.revokedAt), isNull(users.deletedAt))); return ok(request, { items: rows.map(({ accessJti, ...row }) => row) }); });
  route.delete("/online-users/:id", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "强制用户下线", params: idParams } }, async (request) => { const actor = await assertPermission(request, "monitor:online:kick"); const [token] = await app.db.update(refreshTokens).set({ revokedAt: new Date() }).where(and(eq(refreshTokens.id, request.params.id), isNull(refreshTokens.revokedAt))).returning(); if (!token) throw new NotFoundError("在线会话不存在"); if (token.accessJti) { const ttl = Math.max(1, Math.ceil((token.expiresAt.getTime() - Date.now()) / 1000)); await app.redis.set(`auth:access:blacklist:${token.accessJti}`, "1", "EX", ttl); } await writeAuditLog({ db: app.db, request, actor, action: "online_user.kicked", targetType: "refresh_token", targetId: token.id }); return ok(request, { message: "用户已强制下线" }); });

  route.get("/cache/info", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "获取 Redis 状态" } }, async (request) => { await assertPermission(request, "monitor:cache:list"); const [info, dbsize] = await Promise.all([app.redis.info(), app.redis.dbsize()]); return ok(request, { connected: app.redis.status === "ready", dbsize, info }); });
  route.get("/cache/keys", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "查询缓存 Key", querystring: z.object({ prefix: z.string().trim().min(1).max(80), limit: z.coerce.number().int().min(1).max(200).default(100) }) } }, async (request) => { await assertPermission(request, "monitor:cache:list"); assertWhiteListKey(request.query.prefix); const keys: string[] = []; let cursor = "0"; do { const [next, batch] = await app.redis.scan(cursor, "MATCH", `${request.query.prefix}*`, "COUNT", 100); cursor = next; keys.push(...batch); } while (cursor !== "0" && keys.length < request.query.limit); const items = await Promise.all(keys.slice(0, request.query.limit).map(async (key) => ({ key, type: await app.redis.type(key), ttl: await app.redis.ttl(key), size: await app.redis.memory("USAGE", key) }))); return ok(request, { items }); });
  route.delete("/cache/keys", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "删除缓存 Key", body: z.object({ key: z.string().min(1).max(200) }) } }, async (request) => { const actor = await assertPermission(request, "monitor:cache:remove"); assertWhiteListKey(request.body.key); const removed = await app.redis.del(request.body.key); await writeAuditLog({ db: app.db, request, actor, action: "cache.key_deleted", targetType: "redis_key", afterJson: { key: request.body.key, removed } }); return ok(request, { message: removed ? "缓存删除成功" : "缓存不存在", removed }); });

  route.get("/jobs", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "查询异步任务", querystring: paginationQuerySchema } }, async (request) => { await assertPermission(request, "monitor:job:list"); const { skip, take } = getPagination(request.query.page, request.query.pageSize); const [items, [totalRow]] = await Promise.all([app.db.select().from(cronExecutions).orderBy(desc(cronExecutions.createdAt)).offset(skip).limit(take), app.db.select({ value: count() }).from(cronExecutions)]); return ok(request, { items, total: totalRow?.value ?? 0, page: request.query.page, pageSize: request.query.pageSize }); });
  route.get("/cron-jobs", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "查询定时任务" } }, async (request) => { await assertPermission(request, "monitor:job:list"); return ok(request, { items: await app.db.select().from(cronJobs).orderBy(desc(cronJobs.createdAt)) }); });
  route.post("/cron-jobs", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "创建定时任务", body: cronBody } }, async (request) => { const actor = await assertPermission(request, "monitor:job:add"); const [job] = await app.db.insert(cronJobs).values({ ...request.body, createdById: actor.id }).returning(); if (job!.status === "RUNNING") await app.queues.maintenance.upsertJobScheduler(`cron:${job!.id}`, { pattern: job!.cronExpression }, { name: job!.jobType, data: job!.payload ?? {} }); await writeAuditLog({ db: app.db, request, actor, action: "cron_job.created", targetType: "cron_job", targetId: job!.id, afterJson: job }); return ok(request, { message: "定时任务创建成功", job }); });
  route.patch("/cron-jobs/:id/status", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "修改定时任务状态", params: idParams, body: z.object({ status: z.enum(["PAUSED", "RUNNING", "DISABLED"]) }) } }, async (request) => { const actor = await assertPermission(request, "monitor:job:edit"); const [job] = await app.db.update(cronJobs).set({ status: request.body.status, updatedAt: new Date() }).where(eq(cronJobs.id, request.params.id)).returning(); if (!job) throw new NotFoundError("定时任务不存在"); if (job.status === "RUNNING") await app.queues.maintenance.upsertJobScheduler(`cron:${job.id}`, { pattern: job.cronExpression }, { name: job.jobType, data: job.payload ?? {} }); else await app.queues.maintenance.removeJobScheduler(`cron:${job.id}`); await writeAuditLog({ db: app.db, request, actor, action: "cron_job.status_changed", targetType: "cron_job", targetId: job.id, afterJson: { status: job.status } }); return ok(request, { message: "定时任务状态修改成功", job }); });
  route.post("/cron-jobs/:id/run", { preHandler: [app.authenticate], schema: { tags: ["B端 / 平台 / 审计监控"], summary: "立即执行定时任务", params: idParams } }, async (request) => { const actor = await assertPermission(request, "monitor:job:run"); const [job] = await app.db.select().from(cronJobs).where(eq(cronJobs.id, request.params.id)).limit(1); if (!job) throw new NotFoundError("定时任务不存在"); const [execution] = await app.db.insert(cronExecutions).values({ cronJobId: job.id }).returning(); const queueJob = await app.queues.maintenance.add(job.jobType, { ...(job.payload ?? {}), executionId: execution!.id }, { jobId: `cron:${job.id}:${Date.now()}` }); const [updatedExecution] = await app.db.update(cronExecutions).set({ bullJobId: String(queueJob.id) }).where(eq(cronExecutions.id, execution!.id)).returning(); await writeAuditLog({ db: app.db, request, actor, action: "cron_job.run", targetType: "cron_job", targetId: job.id }); return ok(request, { message: "定时任务已加入队列", execution: updatedExecution }); });
}
